Repository zeek/zeek, pull requests merged in 2019-10, with the labels that each got.

#613 Fix build with external CAF but bundled Broker
  CMakeLists.txt
Labels: Area: Broker, Area: Build/Platform, Type: Bug :bug:

#615 Add new BIF: print_raw()
  src/zeek.bif
  testing/btest/Baseline/bifs.print_raw/out
  testing/btest/bifs/print_raw.zeek
Labels: Type: Enhancement

#645 Prefer cmake3 command, add --cmake=PATH option
  configure
Labels: Area: Build/Platform

#669 Add --libdir convenience flag to configure.
  configure
Labels: Area: Build/Platform, Type: Enhancement

#670 Remove "using namespace std" from header files
  src/Anon.h
  src/BroString.h
  src/DFA.h
  src/Debug.h
  src/DebugCmds.h
  src/Desc.h
  src/ID.h
  src/PacketDumper.h
  src/RE.h
  src/Rule.h
  src/Scope.h
  src/SerializationFormat.h
  src/SmithWaterman.h
  src/Type.h
  src/input.h
  src/module_util.cc
  src/module_util.h
  src/probabilistic/BloomFilter.h
Labels: Type: Maintenance

#673 Fix Travis CI script to run Coverity build in container
  testing/scripts/travis-job
Labels: Type: Maintenance
