Repository zeek/zeek, pull requests merged in 2019-11, with the labels that each got.

#675 Allow record_fields() string arguments that name a record type
  src/Type.cc
  src/Type.h
  src/Val.cc
  src/Val.h
  src/zeek.bif
  testing/btest/Baseline/bifs.records_fields/out
  testing/btest/bifs/records_fields.zeek
Labels: Area: Scripting, Type: Enhancement

#683 Print full container types in record_fields()
  src/Type.cc
  testing/btest/Baseline/bifs.records_fields/out
  testing/btest/bifs/records_fields.zeek
Labels: Area: Scripting, Type: Enhancement

#686 Add hint to run make distclean if configure fails
  configure
Labels: Area: Build/Platform, Type: Enhancement

#690 Run unit tests (doctest) on Travis CI
  testing/scripts/travis-job
Labels: Area: CI/Testing, Type: Maintenance

#678 Fix ZEEK_PROFILER_FILE file format/parsing
  src/Brofiler.cc
  src/Brofiler.h
  testing/btest/Baseline/coverage.zeek-profiler-file/step1.out
  testing/btest/Baseline/coverage.zeek-profiler-file/step2.out
  testing/btest/Baseline/coverage.zeek-profiler-file/step3.out
  testing/btest/coverage/zeek-profiler-file.zeek
Labels: Area: Scripting, Type: Bug :bug:
