Repository zeek/zeek, pull requests merged in 2020-01, with the labels that each got.

#749 Improve FTP word/whitespace handling
  src/analyzer/protocol/ftp/FTP.cc
Labels: Area: Protocol Analysis

#747 Improve creation of SMB transaction data strings
  src/analyzer/protocol/smb/smb1-com-transaction.pac
Labels: Area: Protocol Analysis, Type: Bug :bug:

#746 Use consistent zeek_init priority for Log::create_stream calls
  scripts/base/frameworks/signatures/main.zeek
  scripts/policy/files/x509/log-ocsp.zeek
  scripts/policy/protocols/conn/known-hosts.zeek
Labels: Area: Scripting, Type: Bug :bug:

#757 Update Cirrus CI config to use macOS Catalina
  .cirrus.yml
Labels: Area: CI/Testing

#764 Optimize normalize_path
  src/util.cc
  src/util.h
Labels: Type: Enhancement

#763 util: optimize expand_escape() by avoiding sscanf()
  src/util.cc
Labels: Type: Enhancement
