Repository zeek/zeek, pull requests merged in 2020-04, with the labels that each got.

#892 Allow alternate event/hook prototype declarations
  CHANGES
  VERSION
  scripts/base/frameworks/netcontrol/non-cluster.zeek
  scripts/policy/frameworks/netcontrol/catch-and-release.zeek
  src/Func.cc
  src/ID.cc
  src/Type.cc
  src/Type.h
  src/Var.cc
  testing/btest/Baseline/language.alternate-event-hook-prototypes-invalid-arg/out
  testing/btest/Baseline/language.alternate-event-hook-prototypes/out
  testing/btest/Baseline/language.alternate-prototypes-arg-matching/out
  testing/btest/Baseline/language.alternate-prototypes-default-args/errors
  testing/btest/Baseline/language.alternate-prototypes-default-args/out
  testing/btest/Baseline/language.ineffective-default-args/out
  testing/btest/Baseline/language.undeclared-alternate-event-hook-prototype/out
  testing/btest/language/alternate-event-hook-prototypes-invalid-arg.zeek
  testing/btest/language/alternate-event-hook-prototypes.zeek
  testing/btest/language/alternate-prototypes-arg-matching.zeek
  testing/btest/language/alternate-prototypes-default-args.zeek
  testing/btest/language/ineffective-default-args.zeek
  testing/btest/language/undeclared-alternate-event-hook-prototype.zeek
Labels: Area: Scripting, Type: Enhancement

#934 Unused variable assignments found via use-def analysis
  scripts/base/frameworks/cluster/setup-connections.zeek
  scripts/base/frameworks/netcontrol/main.zeek
  scripts/base/frameworks/netcontrol/plugins/openflow.zeek
  scripts/base/protocols/smtp/main.zeek
  scripts/base/utils/addrs.zeek
Labels: Area: Scripting

#930 Remove error message from empty bloomfilter lookups
  src/probabilistic/bloom-filter.bif
  testing/btest/Baseline/bifs.bloomfilter/output
  testing/btest/bifs/bloomfilter.zeek
Labels: Area: Scripting, Type: Bug :bug:

#933 bug fixes for using "when" in functions that have a local of type "any"
  src/Type.cc
  src/Type.h
  src/Val.cc
  testing/btest/Baseline/language.any-when/out
  testing/btest/language/any-when.zeek
Labels: Area: Scripting, Type: Bug :bug:
