Repository zeek/zeek, pull requests merged in 2020-10, with the labels that each got.

#1218 Remove superfluous RuleCondition destructors
  src/RuleCondition.h
Labels: Type: Maintenance

#1206 Silence Clang's warning about ignoring GCC's maybe-uninitialized warning
  src/Val.cc
Labels: Type: Maintenance

#1220 GH-1063: Update libkqueue to fix pf_ring-zc failures
  CHANGES
  VERSION
Labels: Area: Packet Capture, Type: Bug :bug:, Type: Maintenance

#1232 Add header length check to GRE packet analyzer
  src/packet_analysis/protocol/gre/GRE.cc
Labels: Area: Protocol Analysis, Type: Bug :bug:
