Repository zeek/zeek, pull requests merged in 2020-06, with the labels that each got.

#992 Reduce some #includes, speed up builds
  CHANGES
  VERSION
  src/Anon.cc
  src/CompHash.cc
  src/Desc.cc
  src/NetVar.h
  src/Reporter.h
  src/RuleMatcher.cc
  src/SerializationFormat.cc
  src/Stats.cc
  src/analyzer/protocol/mime/MIME.h
  src/analyzer/protocol/tcp/TCP_Endpoint.cc
  src/bro-bif.h
  src/broker/Data.cc
  src/broker/Data.h
  src/broker/Manager.cc
  src/broker/Manager.h
  src/input/Manager.cc
  src/logging/Manager.cc
  src/threading/Manager.cc
  src/threading/MsgThread.h
  src/threading/SerialTypes.cc
  src/util.cc
  src/zeek-setup.cc
  src/zeekygen/ScriptInfo.cc
Labels: Type: Maintenance

#1010 Fix Reporter::conn_weird() to handle expired connections
  scripts/base/frameworks/notice/weird.zeek
  src/Reporter.cc
  src/Reporter.h
  src/Timer.cc
  src/Timer.h
  src/event.bif
  src/reporter.bif
  testing/btest/Baseline/core.expired-conn-weird/out
  testing/btest/core/expired-conn-weird.zeek
Labels: Area: Protocol Analysis, Type: Bug :bug:

#1028 Allow copying/cloning of `opaque of Broker::Store`
  src/broker/Store.h
  testing/btest/Baseline/broker.store.handle-copy/master.out
  testing/btest/broker/store/handle-copy.zeek
Labels: Area: Broker, Area: Scripting, Type: Bug :bug:

#1031 Fix shadowed variable that breaks lookup_hostname()
  src/DNS_Mgr.cc
Labels: Area: Scripting, Type: Bug :bug:

#1026 Fix "possibly-truncated" compiler warning in BuildJSON snprintf()
  src/threading/formatters/JSON.cc
Labels: Area: Build/Platform, Type: Maintenance
