Repository zeek/zeek, pull requests merged in 2020-12, with the labels that each got.

#1320 Update Debug.cc to use setsignal() wrapper
  src/Debug.cc
Labels: Type: Maintenance

#1325 Update Mozilla Root Store
  scripts/base/protocols/ssl/ct-list.zeek
  scripts/base/protocols/ssl/mozilla-ca-list.zeek
Labels: Type: Maintenance

#1327 Add a note about the support matrix to .cirrus.yml
  .cirrus.yml
Labels: Area: CI/Testing, Area: Documentation, Type: Maintenance

#1331 Improve behavior of Dictionary iterator invalidation
  src/Dict.cc
  src/Dict.h
  src/Expr.cc
  src/Val.cc
  src/Val.h
  testing/btest/Baseline/language.table-set-iterator-invalidation/out
  testing/btest/language/table-set-iterator-invalidation.zeek
Labels: Area: Scripting, Type: Enhancement

#1334 Remove explicit use of config mode for finding CAF
  CHANGES
  CMakeLists.txt
  VERSION
Labels: Type: Maintenance

#1341 Fix subtle race on data store initialization
  scripts/base/frameworks/cluster/broker-stores.zeek
Labels: Area: Broker, Type: Bug :bug:
