Repository zeek/zeek, pull requests merged in 2020-11, with the labels that each got.

#1277 Change SizeExpr to yield "any" type when operating on "any"
  src/Expr.cc
  testing/btest/Baseline/language.sizeof-any/error
  testing/btest/Baseline/language.sizeof-any/output
  testing/btest/language/sizeof-any.zeek
Labels: Area: Scripting, Type: Bug :bug:

#1305 Update .gitignore to ignore pyenv .python-version
  .gitignore
Labels: Type: Maintenance

#1313 Remove Fedora 31 (EOL) from CI
  .cirrus.yml
  ci/fedora-31/Dockerfile
Labels: Area: CI/Testing, Type: Maintenance
