Repository zeek/zeek, pull requests merged in 2021-04, with the labels that each got.

#1489 Prep work for Script Compilation: Minor Changes
  scripts/base/frameworks/openflow/consts.zeek
  src/Expr.cc
  src/Type.cc
  src/Type.h
  src/Val.cc
  src/Val.h
  src/parse.y
  src/script_opt/ProfileFunc.cc
  src/script_opt/ProfileFunc.h
  src/script_opt/ScriptOpt.cc
Labels: Area: Scripting, Type: Maintenance

#1505 Improve &expire_func compatibility type-checking
  src/Attr.cc
  src/Type.cc
  src/Type.h
  src/Val.cc
  testing/btest/Baseline/language.expire-func-type-check/output
  testing/btest/language/expire-func-type-check.zeek
Labels: Area: Scripting, Type: Bug :bug:

#1511 Tolerate junk data before SIP requests
  src/analyzer/protocol/sip/sip-analyzer.pac
  src/analyzer/protocol/sip/sip-protocol.pac
  testing/btest/Baseline/scripts.base.protocols.sip.junk/sip.log
  testing/btest/Baseline/scripts.base.protocols.sip.junk/weird.log
  testing/btest/Traces/sip/sip-junk-before-request.pcap
  testing/btest/scripts/base/protocols/sip/junk.zeek
Labels: Area: Protocol Analysis
